# implementation by https://github.com/doobidoo/mcp-memory-service
install-memory-service:
	pipx-install mcp-memory-service
	pipx inject mcp-memory-service onnxruntime
upgrade-memory-service:
	pipx upgrade mcp-memory-service


# skills

skill-mattpocock-improve-codebase-architecture:
	ai-files skill-add mattpocock/skills/improve-codebase-architecture

skill-juliusbrussee-caveman:
	ai-files skills-add JuliusBrussee/caveman --all
